name: Publish updates as GitHub Release assets

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dist
        run: |
          set -euo pipefail
          test -f updates/scan_gui.py || { echo "updates/scan_gui.py not found" >&2; exit 1; }
          test -f updates/VERSION || { echo "updates/VERSION not found" >&2; exit 1; }
          mkdir -p dist
          cp updates/VERSION dist/VERSION
          cp updates/scan_gui.py dist/scan_gui.py
          (cd dist && sha256sum scan_gui.py > scan_gui.py.sha256)
          
          # Inject GitHub token into install script
          sed "s/{{GITHUB_TOKEN_RO}}/${{ secrets.GITHUB_TOKEN_RO }}/g" scripts/install.sh > dist/install.sh
          chmod +x dist/install.sh

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            dist/scan_gui.py
            dist/scan_gui.py.sha256
            dist/VERSION
            dist/install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
